function Productos() {
    return ( 
        <>
            <div className="p-2 m-2 text-center bg-gradient-to-r from-sky-800 to-teal-500 text-white text-2xl">
                <h2>Nos centramos en dar lo mejor del mercado para todos nuestros clientes, a continuacion podrás ver los servicios disponibles</h2>
                <div className="p-2 m-2 flex"><img src="../../public/img/serv1.jpg" alt="servicio 1" height="400" width="400"/><p className="p-2 m-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet.</p></div>
                <div className="p-2 m-2 flex"><p className="p-2 m-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet.</p><img src="../../public/img/servicio2.webp" alt="servicio 1" height="400" width="400"/></div>
                <div className="p-2 m-2 flex"><img src="../../public/img/serv3.webp" alt="servicio 1" height="400" width="400"/><p className="p-2 m-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet.</p></div>
                <div className="p-2 m-2 flex"><p className="p-2 m-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce id tortor nibh. Suspendisse varius tellus ac nisi aliquam semper. Sed in leo ultrices, gravida velit nec, tristique libero. Fusce posuere, leo sit amet semper ultricies, nibh mauris aliquet justo, sagittis lobortis erat ex ac odio. Phasellus sodales quis est quis imperdiet.</p><img src="../../public/img/serv4.jpg" alt="servicio 1" height="400" width="400"/></div>
            </div>
        </>
     );
}

export default Productos;